import { VirtualRoomMember, VirtualRoomRepository, VirtualStudyRoom } from './types';
const KEY='konkur_virtual_rooms_v2'; const now=()=>new Date().toISOString(); const clone=<T,>(v:T):T=>JSON.parse(JSON.stringify(v)) as T;
const member=(studentId:string,displayName:string,totalStudySeconds:number,role:VirtualRoomMember['role']='member'):VirtualRoomMember=>({studentId,displayName,role,totalStudySeconds,joinedAt:now(),status:totalStudySeconds>0?'studying':'offline'});
const seeds=():VirtualStudyRoom[]=>[
 {id:'room-mine',slug:'my-focus-room',name:'اتاق تمرکز من',description:'برنامه‌ریزی روزانه و مطالعه گروهی',ownerId:'local-student',visibility:'private',capacity:30,createdAt:now(),updatedAt:now(),members:[member('local-student','شما',7200,'owner'),member('student-yas','یاسمن',14800),member('student-ali','علی',12600)],requests:[{id:'request-demo',roomId:'room-mine',studentId:'student-nika',displayName:'نیکا',status:'pending',createdAt:now()}]},
 {id:'room-deep',slug:'puzzle-focus',name:'مطالعه عمیق',description:'جلسه‌های آرام برای تمرکز پیوسته',ownerId:'student-raha',visibility:'public',capacity:30,createdAt:now(),updatedAt:now(),members:[member('student-raha','رها',15420,'owner'),member('student-arian','آرین',12115),member('student-sara','سارا',10081)],requests:[]},
 {id:'room-bio',slug:'biology-club',name:'باشگاه زیست',description:'مرور و تست زیست‌شناسی',ownerId:'student-sara',visibility:'private',capacity:20,createdAt:now(),updatedAt:now(),members:[member('student-sara','سارا',13620,'owner'),member('student-nima','نیما',8800)],requests:[]}
];
class LocalVirtualRoomRepository implements VirtualRoomRepository{
 private read(){try{const r=localStorage.getItem(KEY);if(r)return JSON.parse(r) as VirtualStudyRoom[]}catch{}const x=seeds();this.write(x);return x} private write(x:VirtualStudyRoom[]){try{localStorage.setItem(KEY,JSON.stringify(x))}catch{}}
 async listRooms(){return clone(this.read())}
 async createRoom(input:Pick<VirtualStudyRoom,'name'|'slug'|'description'|'visibility'|'capacity'>,owner:VirtualRoomMember){const rooms=this.read(),slug=input.slug.trim().toLowerCase().replace(/[^a-z0-9_-]+/g,'-');if(!slug||rooms.some(r=>r.slug===slug))throw new Error('این شناسه قبلاً استفاده شده است.');const room:VirtualStudyRoom={...input,slug,id:`room-${Date.now()}`,ownerId:owner.studentId,members:[{...owner,role:'owner'}],requests:[],createdAt:now(),updatedAt:now()};rooms.unshift(room);this.write(rooms);return clone(room)}
 async joinPublicRoom(roomId:string,m:VirtualRoomMember){const rooms=this.read(),room=rooms.find(r=>r.id===roomId);if(!room||room.visibility!=='public')throw new Error('ورود مستقیم به این اتاق ممکن نیست.');if(!room.members.some(x=>x.studentId===m.studentId))room.members.push(m);room.updatedAt=now();this.write(rooms);return clone(room)}
 async requestMembership(roomId:string,studentId:string,displayName:string){const rooms=this.read(),room=rooms.find(r=>r.id===roomId);if(!room)throw new Error('اتاق پیدا نشد.');const old=room.requests.find(x=>x.studentId===studentId&&x.status==='pending');if(old)return clone(old);const req={id:`request-${Date.now()}`,roomId,studentId,displayName,status:'pending' as const,createdAt:now()};room.requests.unshift(req);room.updatedAt=now();this.write(rooms);return clone(req)}
 async reviewMembership(roomId:string,requestId:string,reviewerId:string,approve:boolean){const rooms=this.read(),room=rooms.find(r=>r.id===roomId);if(!room||!room.members.some(x=>x.studentId===reviewerId&&['owner','admin'].includes(x.role)))throw new Error('اجازه مدیریت این اتاق را نداری.');const req=room.requests.find(x=>x.id===requestId);if(!req)throw new Error('درخواست پیدا نشد.');req.status=approve?'approved':'rejected';req.reviewedAt=now();req.reviewedBy=reviewerId;if(approve&&!room.members.some(x=>x.studentId===req.studentId))room.members.push(member(req.studentId,req.displayName,0));room.updatedAt=now();this.write(rooms);return clone(room)}
 async addMember(roomId:string,m:VirtualRoomMember,actorId:string){const rooms=this.read(),room=rooms.find(r=>r.id===roomId);if(!room||!room.members.some(x=>x.studentId===actorId&&['owner','admin'].includes(x.role)))throw new Error('اجازه افزودن عضو را نداری.');if(!room.members.some(x=>x.studentId===m.studentId))room.members.push(m);room.updatedAt=now();this.write(rooms);return clone(room)}
 async recordStudy(roomId:string,studentId:string,seconds:number){const rooms=this.read(),room=rooms.find(r=>r.id===roomId),m=room?.members.find(x=>x.studentId===studentId);if(!room||!m)throw new Error('عضویت اتاق پیدا نشد.');m.totalStudySeconds+=Math.max(0,seconds);room.updatedAt=now();this.write(rooms);return clone(room)}
}
export const virtualRoomRepository=new LocalVirtualRoomRepository();
