import React, { useEffect, useMemo, useState } from 'react';
import { BellRing, BookOpen, ChevronLeft, ExternalLink, Flame, Leaf, RefreshCw, ShieldCheck, Sparkles } from 'lucide-react';

type NewsItem={title:string;date:string;url:string;tag:string};
const quotes=['امروز فقط یک قدم؛ همین قدم مسیرت را عوض می‌کند.','تمرکزت را روی همین صفحه نگه دار، نه روی کل مسیر.','هر تست، یک قدم نزدیک‌تر به نسخه قوی‌تر توست.','قرار نیست کامل شروع کنی، قرار است شروع کنی.','آرام جلو برو؛ استمرار از هیجان ماندگارتر است.','وقتی خسته‌ای، هدف را کوچک کن، نه رؤیا را.','تو با ساعت‌های عمیق ساخته می‌شوی، نه با ساعت‌های شلوغ.','هر مرور کوتاه، حافظه‌ات را محکم‌تر می‌کند.','امروز را ذخیره کن؛ فردا به آن تکیه می‌کنی.','نمره نتیجه است، عادت موتور حرکت.','ده دقیقه شروع کن، ادامه‌اش خودش پیدا می‌شود.','مقایسه را خاموش کن؛ مسیر تو مخصوص خودت است.','سؤال سخت، دشمن تو نیست؛ مربی توست.','کمی بهتر از دیروز، دقیقاً کافی است.','اگر حواست رفت، با مهربانی برگرد.','هدف بزرگ با کارهای کوچک روزانه ساخته می‌شود.','به خودت فرصت بده، یادگیری زمان می‌خواهد.','هر صفحه‌ای که می‌خوانی، به اعتمادبه‌نفست اضافه می‌کند.','امروز لازم نیست همه‌چیز را حل کنی.','تو هنوز در حال ساختن نتیجه‌ای هستی که می‌خواهی.'];
const fallback:NewsItem[]=[
 {title:'اطلاعیه‌های ثبت‌نام و تغییرات آزمون سراسری ۱۴۰۵ را فقط از سنجش دنبال کن.',date:'منبع رسمی',url:'https://www.sanjesh.org',tag:'سنجش'},
 {title:'تقویم آزمون‌های آزمایشی و اعلام نتایج مؤسسه‌ات را بررسی کن.',date:'منبع رسمی مؤسسه',url:'https://www.mazems.ir',tag:'آزمون‌ها'},
 {title:'دفترچه‌ها، کارت ورود به جلسه و اصلاحیه‌ها در درگاه رسمی منتشر می‌شوند.',date:'یادآوری',url:'https://www.sanjesh.org',tag:'سنجش'},
];

export const MotivationStrip:React.FC=()=>{const [index,setIndex]=useState(()=>Math.floor(Math.random()*quotes.length));useEffect(()=>{const t=window.setInterval(()=>setIndex(i=>(i+1)%quotes.length),7000);return()=>window.clearInterval(t)},[]);return <section className="motivation-strip" dir="rtl"><span className="motivation-sprout"><Leaf/></span><div><small>یادآوری امروز</small><strong key={index}>{quotes[index]}</strong></div></section>};

export const HomeUpdates:React.FC=()=>{const [items,setItems]=useState<NewsItem[]>(fallback);const [active,setActive]=useState(0);const [loading,setLoading]=useState(false);const [synced,setSynced]=useState(false);
 const load=async()=>{setLoading(true);try{const sources=[{url:'https://www.sanjesh.org',tag:'سنجش'},{url:'https://www.mazems.ir',tag:'آزمون‌ها'}];const fresh:NewsItem[]=[];for(const source of sources){try{const res=await fetch(source.url,{mode:'cors'});if(res.ok)fresh.push({title:`آخرین اطلاعیه‌های ${source.tag} را در منبع رسمی ببین.`,date:'همین حالا',url:source.url,tag:source.tag})}catch{}}if(fresh.length)setItems([...fresh,...fallback]);setSynced(fresh.length>0)}finally{setLoading(false)}};
 useEffect(()=>{void load();},[]);
 useEffect(()=>{if(items.length<2)return;setActive(i=>i%items.length);const t=window.setInterval(()=>setActive(i=>(i+1)%items.length),6500);return()=>window.clearInterval(t)},[items.length]);
 const current=items[active%items.length];return <section className="home-updates" dir="rtl"><div className="updates-heading"><div><span><BellRing/> خبرهای مهم مسیر</span><h2>قبل از بقیه باخبر شو</h2></div><button onClick={()=>void load()} disabled={loading} aria-label="به‌روزرسانی"><RefreshCw className={loading?'spin':''}/></button></div><div className="updates-viewport"><div className="updates-track" style={{transform:`translateX(${active*100}%)`}}>{items.map((item,i)=><a className={`update-card ${item.tag==='سنجش'?'sanjesh':'exam'}`} href={item.url} target="_blank" rel="noreferrer" key={`${item.tag}-${i}`}><span className="update-icon">{item.tag==='سنجش'?<ShieldCheck/>:<BookOpen/>}</span><div><span className="update-source">{item.tag} · {item.date}</span><strong>{item.title}</strong><small>مشاهده منبع رسمی <ExternalLink/></small></div><ChevronLeft/></a>)}</div></div><div className="update-dots">{items.map((_,i)=><button key={i} className={i===active?'active':''} onClick={()=>setActive(i)} aria-label={`خبر ${i+1}`}/>)}</div>{synced&&<small className="updates-sync"><Sparkles/> منابع رسمی با موفقیت تازه‌سازی شدند.</small>}</section>};
